DROP SCHEMA PUBLIC CASCADE;
DROP TABLE STUDENT IF EXISTS;
CREATE TABLE Student (
    Student_ID INT PRIMARY KEY,
    Name VARCHAR(255),
    Email VARCHAR(255),
    Password VARCHAR(255),
    Date_of_Birth DATE,
    PESEL VARCHAR(11)
);

DROP TABLE SOS IF EXISTS;
CREATE TABLE SOS (
    SOS_ID INT PRIMARY KEY,
    Name VARCHAR(255),
    Email VARCHAR(255),
    Password VARCHAR(255),
    Contact_Number VARCHAR(255)
);

DROP TABLE PRZEDMIOT IF EXISTS;
CREATE TABLE PRZEDMIOT (
    Przedmiot_ID INT PRIMARY KEY,
    Name VARCHAR(255)
);

DROP TABLE PROWADZACY IF EXISTS;
CREATE TABLE PROWADZACY (
    Prowadzący_ID INT PRIMARY KEY,
    Name VARCHAR(255),
    Email VARCHAR(255)
);

DROP TABLE KONTO IF EXISTS;
CREATE TABLE KONTO (
    Konto_ID INT PRIMARY KEY,
    Email VARCHAR(255),
    Password VARCHAR(255)
);

DROP TABLE ZAPIS IF EXISTS;
CREATE TABLE ZAPIS (
    Zapis_ID INT PRIMARY KEY,
    Student_ID INT,
    Przedmiot_ID INT,
    Date DATE,
    FOREIGN KEY (Student_ID) REFERENCES Student(Student_ID),
    FOREIGN KEY (Przedmiot_ID) REFERENCES Przedmiot(Przedmiot_ID)
);

DROP TABLE OCENA IF EXISTS;
CREATE TABLE OCENA (
    Ocena_ID INT PRIMARY KEY,
    Student_ID INT,
    Przedmiot_ID INT,
    Value INT,
    FOREIGN KEY (Student_ID) REFERENCES Student(Student_ID),
    FOREIGN KEY (Przedmiot_ID) REFERENCES Przedmiot(Przedmiot_ID)
);
